version: '3.8'

services:
  server:
    build:
      context: ./nest-todo-server
    container_name: server
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/data?
    depends_on:
      - db
    networks:
      - app-network

  client:
    build:
      context: ./todo-app-client
    container_name: client
    ports:
      - '3001:3001'
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
